### ISSUE TITLE
New AWS SSO config format

### ISSUE THREAD

**Issue by aldebout** [thomasmichaelwallace/serverless-better-credentials#18]
**Describe the bug**
This plugin is not compatible with the [new default AWS SSO sessions format](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html#sso-configure-profile-token)

**To Reproduce**
1. Define a new sso session profile with `aws configure sso`
2. Try to deploy a serverless stack with this plugin and the new profile
3. The plugin will try to use the default profile.

**Expected behavior**
The plugin loads the right profile.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version v1.1.2
 - Serverless Version 3.26.0

**Comment by thomasmichaelwallace** [comment]
Hi - 

Thanks for reporting this (and sorry for the slow response!).

Annoyingly it's a bug I'm aware of. Although in this case (unlike #9), it is something that has some support in newer versions of v2 of the aws-sdk (i.e. doesn't require a re-write to v3).

I'll see what I can do!

**Comment by aldebout** [comment]
No worries!

The workaround if anyone is wondering: when running `aws configure sso`, just press Enter without writing anything for the first prompt (`SSO session name (Recommended):`).

**Comment by dk-charter** [comment]
@aldebout Unfortunately that didn't work for me. 

Later: Worked, but I needed to remove all reference to my previously created profile and include 
export AWS_SDK_LOAD_CONFIG=1

**Comment by herebebogans** [comment]
@aldebout your tip is just reverting to legacy configuration mode

**Comment by vicary** [comment]
@aldebout When I have already created a named session, running `aws configure sso` again defaults to that name instead.

My understanding is that you try to create a default session similar to *[profile default]*, I want to try that but I have never seen how a default session looks like in `~/.aws/config`.

Is it called *[sso-session default]*, or is it something else?

**Comment by thomasmichaelwallace** [comment]
This may be addressed in `v1.2.1` - feel free to re-open if not.

**Comment by vicary** [comment]
@thomasmichaelwallace There is a small issue when using [Serverless Compose](https://www.serverless.com/framework/docs/guides/compose). When multiple services try to open up browser window for SSO authentication, only one would actually open.

Running this again would actually fix it because it reuses the now active sso session, but this bug renders CI/CD impossible.

**Comment by obataku** [comment]
@thomasmichaelwallace using `sso-session` + `sso_session` still does not work with 2.0.0 (`AWS provider credentials not found.`); reverting to the [legacy SSO config format](https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-legacy.html) resolves things
