### ISSUE TITLE
The installation command is incorrect

### ISSUE THREAD

**Issue by sakojun** [thomasmichaelwallace/serverless-better-credentials#23]
**Describe the task**

The installation command on this page is incorrect.
https://www.serverless.com/plugins/serverless-better-credentials

`npm install --dev serverless-better-credentials`
↓
`npm install --save-dev serverless-better-credentials`

**Additional context**

**Comment by thomasmichaelwallace** [comment]
Hi - thanks for reporting.

That's not the case in the readme in this repo, so I'll have to work out where that's stored and make the change!

**Comment by sakojun** [comment]
Hi, Thanks for the reply.

I'll write what I notice.

This page is also wrong.
https://www.npmjs.com/package/serverless-better-credentials

README.md was modified some time ago.
https://github.com/thomasmichaelwallace/serverless-better-credentials/commit/2126527518784e334ae4484458bde897575cd899

v1.13 is older than that.
https://github.com/thomasmichaelwallace/serverless-better-credentials/releases/tag/v1.1.3

**Comment by thomasmichaelwallace** [comment]
This may be addressed in `v1.2.1` - feel free to re-open if not.
