### ISSUE TITLE
AWS SSO profile

### ISSUE THREAD

**Issue by alaexeyshustov** [thomasmichaelwallace/serverless-better-credentials#28]
https://github.com/thomasmichaelwallace/serverless-better-credentials/blame/5c2429eaad33863dd4b01aa4b464f243eb0dd529/src/SsoCredentials/getSsoConfig.ts#L27

It's a bug, the function trying to open a flag instead of file

**Comment by thomasmichaelwallace** [comment]
This may be addressed in `v1.2.1` - feel free to re-open if not.
